import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <div className="page-container">
            <div className="flex items-center justify-between font-sans w-full">
              <div className="logo text-2xl font-bold">devFeed</div>
              
            </div>
          </div>

        </header>
        <main className="min-h-screen">
        {children}

        </main>
        <footer className="bg-zinc-50 font-sans">
          <div className="page-container">
            <div className="flex items-center justify-between font-sans w-full py-4">
              <p>&copy; 2026 devFeed. All rights reserved.</p>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
