import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Link from "next/link";
import { getOptionalAuth } from "@/lib/auth";
import Logout from "@/components/logout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getOptionalAuth();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <div className="page-container">
            <div className="flex items-center justify-between font-sans w-full">
              <div className="logo text-4xl font-bold">DevFeed</div>
              <div className="flex items-center justify-center font-sans">
                <nav className="flex items-center gap-4">
                  <Link href="/">Home</Link>
                  <Link href={"/dashboard"}>Dashboard</Link>
                  <Link href={"/post/create"}>Create Post</Link>
                </nav>
              </div>
              {user ? <div className="flex items-center justify-center font-sans gap-4">
                  <span className="text-black font-bold">{user.email}</span>
                  <Logout />
                </div> : (
              <div className="flex items-center justify-center font-sans gap-4">
                  <Link href="/login" className="bg-blue-500 text-white px-4 py-2 rounded-md button">Login</Link>
                  <Link href="/register" className="bg-blue-500 text-white px-4 py-2 rounded-md button secondary-button">Register</Link>
                </div>
              )}
            </div>
          </div>

        </header>
        <main className="min-h-screen mb-16">
        {children}

        </main>
        <footer className="bg-zinc-50 font-sans">
          <div className="page-container">
            <div className="flex items-center justify-between font-sans w-full py-4">
              <p>&copy; 2026 devFeed. All rights reserved.</p>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
